name: geobenchmark
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  # required
  - dask-geopandas
  - geofileops
  - geopandas
  - geowombat
  - pygeoprocessing
  - rasterstats
  # linting
  - black =23
  - ruff
  - pre-commit